server:
  port: 8093
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
  jackson:
    serialization:
      write-dates-as-timestamps: false
  date-format: java.txt.SimpleDateFormat
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true