server:
  port: 8093
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
jwt:
  secret: lucamusic
  jwtExpirationInMs: 18000000
spring:
  datasource:
    url: jdbc:mysql://localhost/users?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: GEObbdd93@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/